In [1]:
import numpy as np

In [2]:
np.random.seed(42)

In [161]:
xt = np.random.randn(3, 5)
wx = np.random.randn(10, 3)
a0 = np.random.randn(4, 5)
wa = np.random.randn(10, 4)
wy = np.random.randn(5, 10)
ba = np.random.randn(10, 5)
by = np.random.randn(5, 5)

params = {"wx": wx, "wa": wa, "wy": wy, "ba": ba, "by": by}

In [162]:
def softmax(x):
    pred = np.zeros((x.shape[0], x.shape[1]))
    
    for y, i in enumerate(x):
        pred[y] = np.exp(i)/np.sum(np.exp(i))
        #pred[i] = np.exp(x[i])/np.sum(np.exp(x[i]))
        
    return pred

In [163]:
x = np.random.randn(5, 6)
y = softmax(x)
print(y)

for i in y:
    print(np.sum(i))

[[0.17558611 0.06462289 0.48736694 0.06272385 0.10432485 0.10537534]
 [0.07674187 0.22517876 0.07965789 0.44068191 0.04822723 0.12951235]
 [0.06036336 0.19976487 0.1290524  0.1122924  0.43036911 0.06815785]
 [0.35113571 0.09053149 0.2186217  0.05909122 0.10069947 0.17992041]
 [0.32202611 0.05801997 0.27441781 0.06538591 0.03561971 0.24453049]]
0.9999999999999999
1.0
0.9999999999999998
1.0
1.0


In [164]:
def rnn_def(xt, a_next, parameters):
    wx = parameters["wx"]
    wa = parameters["wa"]
    wy = parameters["wy"]
    by = parameters["by"]
    ba = parameters["ba"]

    hidden_s = np.tanh(np.add(np.dot(wx, xt), np.dot(wa, a_next), ba))
    
    y_ = softmax(np.add(np.dot(wy, hidden_s), by))
    
    return (hidden_s, y_)

In [165]:
rnn_def(xt, a0, params)

(array([[-0.17738095, -0.05642125, -0.98948517, -0.8697797 ,  0.72562301],
        [-0.57383772, -0.94997017,  0.72658419,  0.99906576,  0.25478837],
        [-0.70577364, -0.99666834,  0.41655705, -0.20908389,  0.92507698],
        [-0.8358413 ,  0.99842233, -0.84343241, -0.95959836,  0.99380288],
        [-0.52912518,  0.99571229, -0.83267781,  0.99999938, -0.70297861],
        [ 0.58391896, -0.94569514, -0.94541242, -0.89141283,  0.04752302],
        [-0.91611219,  0.47996606,  0.99956555,  0.89846357,  0.99841729],
        [ 0.92165012, -0.91635631, -0.94257679, -0.99518518,  0.22218849],
        [ 0.73971609,  0.90468204,  0.4822566 ,  0.47684822, -0.8801054 ],
        [ 0.98126641, -0.17745136, -0.9931357 , -0.99837247, -0.98177684]]),
 array([[3.23901974e-01, 2.18336367e-01, 1.75373622e-03, 6.65797911e-03,
         4.49349943e-01],
        [2.30481414e-03, 6.39845929e-01, 4.35119921e-03, 3.53430919e-01,
         6.71386666e-05],
        [5.80932399e-05, 5.09402983e-02, 4.7755383

In [166]:
xt = np.random.randn(3, 5, 4)
wx = np.random.randn(10, 3)
a0 = np.random.randn(4, 5)
wa = np.random.randn(10, 4)
wy = np.random.randn(5, 10)
ba = np.random.randn(10, 5)
by = np.random.randn(5, 5)

params = {"wx": wx, "wa": wa, "wy": wy, "ba": ba, "by": by}

In [167]:
def rnn_forward(xt, a_next, params):
    Tx = xt.shape[2]
    
    for i in range(Tx):
        hidden_s, y_ = rnn_def(xt[:, :, i], a_next, params)      
        
    return (hidden_s, y_)

In [168]:
hid, y = rnn_forward(xt, a0, params)

In [169]:
print("Hidden state info: \n", hid)
print("\nOutput info: \n", y)

Hidden state info: 
 [[-0.55795929  0.99490595 -0.03291065 -0.99986561  0.56920406]
 [ 0.22899944 -0.72330338  1.          0.99999971  0.99999906]
 [-0.91224602  0.94372598 -0.99983959  0.99878032 -0.99783326]
 [-0.91988577 -0.99411595  0.99968351 -0.0372161   0.99999799]
 [-0.94670258  0.50626751 -0.52180747  0.98478646  0.99855059]
 [-0.91511148  0.65678483  0.81084552 -0.18752748 -0.78564782]
 [ 0.11238975 -0.86254979  0.99636461 -0.99946745  0.49076179]
 [ 0.99650323  0.88520108  0.97324709  0.94278483  0.90645992]
 [-0.99128202 -0.99367185  0.99876273  0.82361281  0.99800197]
 [ 0.98852714  0.99453622 -0.88685304  0.90977358  0.99969876]]

Output info: 
 [[1.76640554e-02 9.75944303e-01 7.72139194e-05 6.26313617e-03
  5.12913953e-05]
 [4.30580392e-02 7.68825972e-01 2.17121597e-03 9.26025140e-02
  9.33422588e-02]
 [7.44983614e-04 9.76049085e-01 1.97552002e-02 3.24199569e-03
  2.08735069e-04]
 [8.83322054e-03 6.19368283e-02 1.46492882e-01 7.70526041e-01
  1.22110288e-02]
 [3.43800723